services:
  cosyvoice:
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   http_proxy: "http://172.17.0.1:7890"
      #   https_proxy: "http://172.17.0.1:7890"
    image: cosyvoice:latest
    container_name: cosyvoice-server
    ports:
      - "50001:50000"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
    tty: true
